### ISSUE TITLE
Отобразить шаблоны в папках.  8 ч

### ISSUE THREAD

**Issue by evgeniikotliarov** [KarambaKG/rack-app#7]
Предыстория:
Админ должен видеть шаблоны лежащие в папках.

Задача:
Реализовать отображение шаблонов находящихся в папках Sms и Email.
Отобразить каждый шаблон из папки.

Методы решения:
Создать несколько шаблонов, каждый шаблон положить в файл в формате Json.
Создать Вьюшку show.html.erb, добавить маршрут к вьюшке из главной страницы.
Обеспечить считывание файла из папки(либо sms, либо email) и отобразить данные шаблона во
вьюшки show.html.erb

Критерий готовности:
Шаблоны сделаны в формате json.
Сделана вьюшка show.html.erb.
Считывание содержимого шаблона и отображение на странице show реализовано.

Админ видит шаблоны в папках

**Comment by KarambaKG** [comment]
Запланировано: 8
